(()=>{'use strict';
const SUPABASE_URL='https://waqobihznhkbspdchjbb.supabase.co';
const SUPABASE_KEY='sb_publishable_uPGjlkbauGtisASevhnTLA_jIJDhzZG';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const BOARD_PAGE_SIZE=20,POST_PAGE_SIZE=15,AVATAR_BUCKET='forum-avatars',MAX_AVATAR_BYTES=10*1024*1024;
const AVATAR_TYPES=new Set(['image/jpeg','image/png','image/webp']);
const EXPECTED_ENTITIES=913,ENTITY_CACHE_KEY='tpw:canonical-entity-index:v4',ENTITY_CACHE_TTL=24*60*60*1000;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const fmt=v=>{if(!v)return'—';try{return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}catch{return String(v)}};
const rel=v=>{if(!v)return'—';const s=Math.max(0,(Date.now()-new Date(v).getTime())/1000);if(s<60)return'just now';if(s<3600)return`${Math.floor(s/60)}m ago`;if(s<86400)return`${Math.floor(s/3600)}h ago`;if(s<604800)return`${Math.floor(s/86400)}d ago`;return fmt(v)};
const clip=(v,n=190)=>String(v??'').replace(/\s+/g,' ').trim().slice(0,n);
const state={session:null,profile:null,categories:[],thread:null,replyTo:null,reportTarget:null,entityIndex:null,routeToken:0};
const isStaff=()=>['moderator','admin'].includes(state.profile?.role),isAdmin=()=>state.profile?.role==='admin';
const displayName=p=>p?.display_name||p?.username||'Unknown member';
const initials=p=>String(displayName(p)).trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase().slice(0,2)||'?';
function flash(message,kind=''){const el=$('#globalNotice');if(!el)return;el.className=`notice ${kind}`.trim();el.textContent=message;el.classList.remove('hidden');clearTimeout(flash.t);flash.t=setTimeout(()=>el.classList.add('hidden'),5200)}
function openModal(sel){$(sel)?.classList.remove('hidden')}
function closeModal(el){(typeof el==='string'?$(el):el)?.classList.add('hidden')}
function badge(role){return role&&role!=='member'?`<span class="status ${esc(role)}">${esc(role).toUpperCase()}</span>`:''}
function avatar(profile,size='sm'){return profile?.avatar_url?`<span class="forum-avatar ${size}"><img src="${esc(profile.avatar_url)}" alt="" loading="lazy" referrerpolicy="no-referrer"></span>`:`<span class="forum-avatar ${size}" aria-hidden="true">${esc(initials(profile))}</span>`}
function statusFlags(t){return`${t.is_pinned?'<span class="status pinned">PINNED</span>':''}${t.is_locked?'<span class="status locked">LOCKED</span>':''}${t.moderation_status&&t.moderation_status!=='visible'?'<span class="status hidden-status">HIDDEN</span>':''}`}
function urlFor(obj={}){const q=new URLSearchParams();for(const[k,v]of Object.entries(obj)){if(v!==undefined&&v!==null&&v!=='')q.set(k,String(v))}return`/forum/${q.size?`?${q.toString()}`:''}`}
function navigate(obj={},replace=false){history[replace?'replaceState':'pushState']({},'',urlFor(obj));window.ForumApp?.route()}
function requireProfile(){if(!state.session){window.ForumCommunity?.showAuth('signin');return false}if(!state.profile){openModal('#profileSetupModal');return false}return true}
function activeTab(view){$$('.forum-tab').forEach(tab=>{const on=tab.dataset.navView===view;tab.setAttribute('aria-selected',String(on));if(on)tab.setAttribute('aria-current','page');else tab.removeAttribute('aria-current')})}
function crumbs(items){$('#breadcrumbs').innerHTML=items.map((x,i)=>`${i?'<span class="crumb-sep">/</span>':''}${x.href?`<a data-route href="${x.href}">${esc(x.label)}</a>`:`<span aria-current="page">${esc(x.label)}</span>`}`).join('')}
function pageHead(kicker,title,description='',action=''){return`<header class="page-head"><div><div class="page-kicker">${esc(kicker)}</div><h2>${esc(title)}</h2>${description?`<p>${esc(description)}</p>`:''}</div>${action?`<div class="page-actions">${action}</div>`:''}</header>`}
function newDiscussionButton(){return'<button class="bbs-btn primary" data-new-thread type="button">NEW DISCUSSION</button>'}
function pager(page,pages,total,param){return`<div class="forum-pagination"><button class="bbs-btn secondary" type="button" data-page-param="${param}" data-page="${page-1}" ${page<=1?'disabled':''}>PREVIOUS</button><span class="page-status">PAGE ${page} OF ${pages} · ${total} ITEMS</span><button class="bbs-btn secondary" type="button" data-page-param="${param}" data-page="${page+1}" ${page>=pages?'disabled':''}>NEXT</button></div>`}
function renderNotFound(message='This forum location could not be found.'){activeTab('home');crumbs([{label:'Forum',href:'/forum/'},{label:'Not found'}]);$('#forumContent').innerHTML=pageHead('404','Forum Location Unavailable',message)+'<section class="panel"><div class="empty-state">RETURN TO <a data-route href="/forum/">FORUM HOME</a>.</div></section>'}
async function refreshAuth(){const{data,error}=await db.auth.getSession();if(error)throw error;state.session=data.session;state.profile=null;if(state.session?.user){const{data:p,error:pe}=await db.from('forum_profiles').select('id,username,display_name,bio,avatar_url,role,created_at').eq('id',state.session.user.id).maybeSingle();if(pe)throw pe;state.profile=p||null}renderAccount()}
function renderAccount(){const bar=$('#accountBar'),bookmarks=$('#bookmarksTab');if(!bar)return;if(!state.session){bookmarks?.classList.add('hidden');bar.innerHTML='<div class="auth-top"><button class="bbs-btn secondary" type="button" data-auth-open="signin">SIGN IN</button><button class="bbs-btn primary" type="button" data-auth-open="register">REGISTER</button></div>';return}if(!state.profile){bookmarks?.classList.add('hidden');bar.innerHTML='<div class="auth-top"><button class="bbs-btn primary" type="button" data-complete-profile>CREATE FORUM PROFILE</button><button class="bbs-btn secondary" type="button" data-signout>SIGN OUT</button></div>';return}bookmarks?.classList.remove('hidden');bar.innerHTML=`<button id="accountChip" class="account-chip" type="button" aria-expanded="false" aria-controls="accountMenu">${avatar(state.profile,'sm')}<span class="account-copy"><strong>${esc(displayName(state.profile))}</strong><span>@${esc(state.profile.username)} ${state.profile.role!=='member'?`· ${esc(state.profile.role.toUpperCase())}`:''}</span></span></button>`;const menu=$('#accountMenu');menu.innerHTML=`<button role="menuitem" data-my-profile>MY PROFILE</button><a role="menuitem" data-route href="${urlFor({view:'bookmarks'})}">MY BOOKMARKS</a><a role="menuitem" data-route href="${urlFor({view:'my-discussions'})}">MY DISCUSSIONS</a><a role="menuitem" data-route href="${urlFor({view:'my-posts'})}">MY POSTS</a><button role="menuitem" data-edit-profile>EDIT PROFILE</button>${isStaff()?'<button role="menuitem" data-staff-console>STAFF CONSOLE</button>':''}<button role="menuitem" data-signout>SIGN OUT</button>`}
function positionAccountMenu(){const chip=$('#accountChip'),menu=$('#accountMenu');if(!chip||!menu||menu.classList.contains('hidden'))return;const r=chip.getBoundingClientRect(),w=Math.min(280,window.innerWidth-20);menu.style.width=`${w}px`;menu.style.top=`${Math.min(window.innerHeight-menu.offsetHeight-10,r.bottom+6)}px`;menu.style.left=`${Math.max(10,Math.min(window.innerWidth-w-10,r.right-w))}px`}
function toggleAccountMenu(){const menu=$('#accountMenu'),chip=$('#accountChip');if(!menu||!chip)return;const open=menu.classList.contains('hidden');menu.classList.toggle('hidden',!open);chip.setAttribute('aria-expanded',String(open));if(open)requestAnimationFrame(positionAccountMenu)}
function closeAccountMenu(){const menu=$('#accountMenu'),chip=$('#accountChip');menu?.classList.add('hidden');chip?.setAttribute('aria-expanded','false')}
async function loadCategories(){const{data,error}=await db.from('forum_categories').select('id,slug,name,description,sort_order,is_locked').order('sort_order');if(error)throw error;state.categories=data||[];$('#threadCategory').innerHTML=state.categories.filter(c=>!c.is_locked).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}
async function refreshStats(){const[m,t,p]=await Promise.all([db.from('forum_profiles').select('*',{count:'exact',head:true}),db.from('forum_threads').select('*',{count:'exact',head:true}).eq('moderation_status','visible'),db.from('forum_posts').select('*',{count:'exact',head:true}).eq('moderation_status','visible')]);$('#forumStats').innerHTML=`<div><strong>${m.count??0}</strong><span>MEMBERS</span></div><div><strong>${t.count??0}</strong><span>THREADS</span></div><div><strong>${p.count??0}</strong><span>POSTS</span></div>`}
async function profiles(ids){ids=[...new Set((ids||[]).filter(Boolean))];if(!ids.length)return new Map();const{data,error}=await db.from('forum_profiles').select('id,username,display_name,bio,avatar_url,role,created_at').in('id',ids);if(error)throw error;return new Map((data||[]).map(p=>[p.id,p]))}
async function threadMetadata(ids){ids=[...new Set((ids||[]).filter(Boolean))];if(!ids.length)return new Map();const{data,error}=await db.rpc('forum_thread_metadata',{p_thread_ids:ids});if(error)throw error;const pm=await profiles((data||[]).map(x=>x.last_post_author_id));return new Map((data||[]).map(x=>[x.thread_id,{posts:Number(x.post_count||0),replies:Number(x.reply_count||0),lastAt:x.last_post_at,lastAuthor:x.last_post_author_id,lastProfile:pm.get(x.last_post_author_id)||null}]))}
async function hydrateThreads(rows){const pm=await profiles((rows||[]).map(x=>x.author_id)),cm=new Map(state.categories.map(c=>[String(c.id),c])),mm=await threadMetadata((rows||[]).map(x=>x.id));return(rows||[]).map(t=>({...t,starter:pm.get(t.author_id)||null,category:cm.get(String(t.category_id))||null,meta:mm.get(t.id)||{posts:0,replies:0,lastAt:t.last_post_at,lastProfile:null}}))}
function threadRow(t){const m=t.meta||{};return`<article class="thread-row"><div class="thread-main"><div class="thread-title-line">${statusFlags(t)}<a class="thread-title" data-route href="${urlFor({thread:t.id})}">${esc(t.title)}</a></div><div class="thread-subline"><a data-route href="${urlFor({category:t.category?.slug})}">${esc(t.category?.name||'Forum')}</a><span>started by <a href="#" data-profile="${t.author_id}">${esc(displayName(t.starter))}</a> ${badge(t.starter?.role)}</span></div></div><div class="thread-stats"><span><strong>${m.replies||0}</strong> replies · <strong>${m.posts||0}</strong> posts</span><span class="thread-last">last by ${esc(displayName(m.lastProfile))} · ${esc(rel(m.lastAt||t.last_post_at))}</span></div></article>`}
async function loadEntityIndex(){if(state.entityIndex)return state.entityIndex;try{const cached=JSON.parse(localStorage.getItem(ENTITY_CACHE_KEY)||'null');if(cached&&Array.isArray(cached.entries)&&cached.entries.length===EXPECTED_ENTITIES&&Date.now()-cached.savedAt<ENTITY_CACHE_TTL){state.entityIndex=cached.entries;return state.entityIndex}}catch{}const res=await fetch('/api/forum-entities',{credentials:'same-origin'});if(!res.ok)throw new Error(`Entity index request failed (${res.status})`);const payload=await res.json(),entries=Array.isArray(payload?.entries)?payload.entries.filter(e=>e&&e.name&&e.slug):[];if(entries.length!==EXPECTED_ENTITIES)throw new Error(`Verified ${entries.length} entities; expected ${EXPECTED_ENTITIES}.`);entries.sort((a,b)=>String(a.name).localeCompare(String(b.name)));state.entityIndex=entries;try{localStorage.setItem(ENTITY_CACHE_KEY,JSON.stringify({savedAt:Date.now(),entries}))}catch{}return entries}
window.ForumCore={SUPABASE_URL,SUPABASE_KEY,db,BOARD_PAGE_SIZE,POST_PAGE_SIZE,AVATAR_BUCKET,MAX_AVATAR_BYTES,AVATAR_TYPES,EXPECTED_ENTITIES,$,$$,esc,fmt,rel,clip,state,isStaff,isAdmin,displayName,initials,flash,openModal,closeModal,badge,avatar,statusFlags,urlFor,navigate,requireProfile,activeTab,crumbs,pageHead,newDiscussionButton,pager,renderNotFound,refreshAuth,renderAccount,positionAccountMenu,toggleAccountMenu,closeAccountMenu,loadCategories,refreshStats,profiles,threadMetadata,hydrateThreads,threadRow,loadEntityIndex};
})();
