(() => {
  const SUPABASE_URL='https://waqobihznhkbspdchjbb.supabase.co';
  const SUPABASE_KEY='sb_publishable_uPGjlkbauGtisASevhnTLA_jIJDhzZG';
  const client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true}});

  const $=s=>document.querySelector(s);
  const els={
    categories:$('#categories'),latest:$('#latestThreads'),mainTitle:$('#mainTitle'),authState:$('#authState'),authActions:$('#authActions'),profileSetup:$('#profileSetup'),usernameInput:$('#usernameInput'),displayNameInput:$('#displayNameInput'),saveProfileBtn:$('#saveProfileBtn'),newThreadBtn:$('#newThreadBtn'),threadView:$('#threadView'),forumHome:$('#forumHome'),breadcrumbs:$('#breadcrumbs'),loginModal:$('#loginModal'),newThreadModal:$('#newThreadModal'),profileModal:$('#profileModal'),staffModal:$('#staffModal'),loginForm:$('#loginForm'),signupForm:$('#signupForm'),newThreadForm:$('#newThreadForm'),threadCategory:$('#threadCategory'),threadTitle:$('#threadTitle'),threadBody:$('#threadBody'),entityId:$('#entityId'),entityName:$('#entityName'),globalNotice:$('#globalNotice'),replyForm:$('#replyForm'),replyBody:$('#replyBody'),threadPosts:$('#threadPosts'),threadHeading:$('#threadHeading'),threadMeta:$('#threadMeta'),threadEntity:$('#threadEntity'),bookmarkBtn:$('#bookmarkBtn'),threadReportBtn:$('#threadReportBtn'),staffThreadTools:$('#staffThreadTools'),profileContent:$('#profileContent'),staffContent:$('#staffContent'),forumStats:$('#forumStats')
  };

  let session=null,profile=null,categories=[],activeThread=null,activePosts=[];
  const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  const fmt=v=>{if(!v)return'';try{return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}catch{return String(v)}};
  const isStaff=()=>profile&&['moderator','admin'].includes(profile.role);
  const isAdmin=()=>profile?.role==='admin';
  const roleBadge=r=>r&&r!=='member'?`<span class="role-badge ${esc(r)}">${esc(r)}</span>`:'';

  function showNotice(message,kind=''){if(!els.globalNotice)return;els.globalNotice.className=`notice ${kind}`.trim();els.globalNotice.textContent=message;els.globalNotice.classList.remove('hidden');clearTimeout(showNotice.timer);showNotice.timer=setTimeout(()=>els.globalNotice.classList.add('hidden'),5200)}
  function openModal(el){el?.classList.remove('hidden')}
  function closeModal(el){el?.classList.add('hidden')}

  async function loadCategories(){const{data,error}=await client.from('forum_categories').select('id,slug,name,description,sort_order,is_locked').order('sort_order');if(error)throw error;categories=data||[];renderCategories();els.threadCategory.innerHTML=categories.filter(c=>!c.is_locked).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}
  function renderCategories(){if(!els.categories)return;els.categories.innerHTML=categories.length?categories.map(c=>`<div class="category-row"><div><div class="category-name"><button type="button" data-category="${esc(c.slug)}">${esc(c.name)}</button></div><div class="category-desc">${esc(c.description)}</div></div><div class="category-meta">${c.is_locked?'LOCKED':'OPEN'}</div></div>`).join(''):'<div class="empty-state">No boards are available.</div>';els.categories.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>loadCategory(b.dataset.category)))}

  async function loadStats(){if(!els.forumStats)return;const [members,threads,posts]=await Promise.all([
    client.from('forum_profiles').select('*',{count:'exact',head:true}),
    client.from('forum_threads').select('*',{count:'exact',head:true}),
    client.from('forum_posts').select('*',{count:'exact',head:true})
  ]);els.forumStats.innerHTML=`<div class="forum-stat"><strong>${members.count??0}</strong><span>MEMBERS</span></div><div class="forum-stat"><strong>${threads.count??0}</strong><span>THREADS</span></div><div class="forum-stat"><strong>${posts.count??0}</strong><span>POSTS</span></div>`}

  async function hydrateThreads(rows){
    if(!rows?.length)return[];
    const authorIds=[...new Set(rows.map(r=>r.author_id).filter(Boolean))];
    const categoryIds=[...new Set(rows.map(r=>r.category_id).filter(v=>v!==null&&v!==undefined))];
    const [profilesResult,categoriesResult]=await Promise.all([
      authorIds.length?client.from('forum_profiles').select('id,username,display_name,role').in('id',authorIds):Promise.resolve({data:[],error:null}),
      categoryIds.length?client.from('forum_categories').select('id,name,slug').in('id',categoryIds):Promise.resolve({data:[],error:null})
    ]);
    if(profilesResult.error)throw profilesResult.error;
    if(categoriesResult.error)throw categoriesResult.error;
    const profileMap=new Map((profilesResult.data||[]).map(p=>[p.id,p]));
    const categoryMap=new Map((categoriesResult.data||[]).map(c=>[String(c.id),c]));
    return rows.map(t=>({...t,forum_profiles:profileMap.get(t.author_id)||null,forum_categories:categoryMap.get(String(t.category_id))||null}));
  }

  async function hydratePosts(rows){
    if(!rows?.length)return[];
    const authorIds=[...new Set(rows.map(r=>r.author_id).filter(Boolean))];
    const profilesResult=authorIds.length?await client.from('forum_profiles').select('id,username,display_name,role,created_at').in('id',authorIds):{data:[],error:null};
    if(profilesResult.error)throw profilesResult.error;
    const profileMap=new Map((profilesResult.data||[]).map(p=>[p.id,p]));
    return rows.map(p=>({...p,forum_profiles:profileMap.get(p.author_id)||null}));
  }

  async function loadLatestThreads(){
    els.latest.innerHTML='<div class="empty-state">Loading recent discussions…</div>';
    try{
      const{data,error}=await client.from('forum_threads').select('id,title,category_id,author_id,created_at,last_post_at,is_pinned,is_locked').order('last_post_at',{ascending:false}).limit(12);
      if(error)throw error;
      renderThreadRows(await hydrateThreads(data||[]),els.latest);
    }catch(error){console.error('Recent thread load failed',error);els.latest.innerHTML='<div class="empty-state">Recent discussions are temporarily unavailable.</div>'}
  }
  function renderThreadRows(rows,target){if(!rows.length){target.innerHTML='<div class="empty-state">No discussions yet. The archive is quiet.</div>';return}target.innerHTML=rows.map(t=>{const author=t.forum_profiles?.display_name||t.forum_profiles?.username||'Unknown member';const flags=`${t.is_pinned?'<span class="thread-flag pin">PINNED</span>':''}${t.is_locked?'<span class="thread-flag lock">LOCKED</span>':''}`;return `<div class="thread-row"><div class="thread-title-wrap"><button class="thread-link thread-title" type="button" data-thread="${t.id}">${esc(t.title)}</button><span class="thread-flags">${flags}</span></div><div class="thread-meta">${esc(t.forum_categories?.name||'Forum')} · ${esc(author)}${roleBadge(t.forum_profiles?.role)} · last activity ${esc(fmt(t.last_post_at))}</div></div>`}).join('');target.querySelectorAll('[data-thread]').forEach(b=>b.addEventListener('click',()=>openThread(b.dataset.thread)))}

  async function loadCategory(slug,push=true){
    const c=categories.find(x=>x.slug===slug);if(!c)return;
    if(push)history.pushState({category:slug},'',`/forum/?category=${encodeURIComponent(slug)}`);
    els.threadView.classList.add('hidden');els.forumHome.classList.remove('hidden');
    els.mainTitle.textContent=c.name;els.categories.innerHTML='<div class="empty-state">Loading discussions…</div>';
    try{
      const{data,error}=await client.from('forum_threads').select('id,title,category_id,author_id,created_at,last_post_at,is_pinned,is_locked').eq('category_id',c.id).order('is_pinned',{ascending:false}).order('last_post_at',{ascending:false}).limit(60);
      if(error)throw error;
      renderThreadRows(await hydrateThreads(data||[]),els.categories);
      renderBreadcrumbs([{label:'Forum',action:showHome},{label:c.name}]);
    }catch(error){console.error('Board thread load failed',error);els.categories.innerHTML='<div class="empty-state">Unable to load this board.</div>'}
  }
  function renderBreadcrumbs(items){els.breadcrumbs.innerHTML='';items.forEach((item,i)=>{if(i)els.breadcrumbs.append(document.createTextNode(' / '));if(item.action){const b=document.createElement('button');b.type='button';b.textContent=item.label;b.addEventListener('click',item.action);els.breadcrumbs.append(b)}else{const s=document.createElement('span');s.textContent=item.label;els.breadcrumbs.append(s)}})}

  async function openThread(id,push=true){
    if(push)history.pushState({thread:id},'',`/forum/?thread=${encodeURIComponent(id)}`);
    els.forumHome.classList.add('hidden');els.threadView.classList.remove('hidden');els.threadPosts.innerHTML='<div class="empty-state">Opening discussion…</div>';
    try{
      const{data:rawThread,error}=await client.from('forum_threads').select('id,title,category_id,author_id,created_at,last_post_at,is_locked,is_pinned,moderation_status').eq('id',id).single();
      if(error||!rawThread)throw error||new Error('Thread not found');
      const hydrated=await hydrateThreads([rawThread]);
      const t=hydrated[0];
      activeThread=t;els.threadHeading.textContent=t.title;
      const author=t.forum_profiles?.display_name||t.forum_profiles?.username||'Unknown member';
      els.threadMeta.innerHTML=`${esc(t.forum_categories?.name||'Forum')} · started by <button class="profile-link" data-profile="${t.author_id}">${esc(author)}</button>${roleBadge(t.forum_profiles?.role)} · ${esc(fmt(t.created_at))}`;
      els.replyForm.classList.toggle('hidden',!session||!profile||t.is_locked);els.threadReportBtn.disabled=!session||!profile;renderStaffThreadTools();
      const{data:links}=await client.from('forum_entity_links').select('entity_id,entity_name').eq('thread_id',id);
      els.threadEntity.innerHTML=(links||[]).map(l=>`<span class="entity-tag" title="Archive entity ID: ${esc(l.entity_id)}">ARCHIVE LINK: ${esc(l.entity_name)}</span>`).join('');
      const{data:rawPosts,error:pe}=await client.from('forum_posts').select('id,body,author_id,reply_to_id,created_at,updated_at,moderation_status').eq('thread_id',id).order('created_at');
      if(pe)throw pe;
      activePosts=await hydratePosts(rawPosts||[]);
      await renderPosts(activePosts);
      renderBreadcrumbs([{label:'Forum',action:showHome},{label:t.forum_categories?.name||'Board',action:()=>loadCategory(t.forum_categories?.slug)},{label:t.title}]);
      await updateBookmarkState();wireProfileLinks(els.threadMeta);
    }catch(error){console.error('Thread load failed',error);els.threadPosts.innerHTML='<div class="empty-state">This discussion could not be loaded.</div>'}
  }

  async function renderPosts(posts){let reactionMap={};if(posts.length){const{data}=await client.from('forum_reactions').select('post_id,user_id,reaction').in('post_id',posts.map(p=>p.id));(data||[]).forEach(r=>{reactionMap[r.post_id]??={like:0,interesting:0,mine:new Set()};reactionMap[r.post_id][r.reaction]=(reactionMap[r.post_id][r.reaction]||0)+1;if(session&&r.user_id===session.user.id)reactionMap[r.post_id].mine.add(r.reaction)})}
    els.threadPosts.innerHTML=posts.map((p,index)=>{const name=p.forum_profiles?.display_name||p.forum_profiles?.username||'Unknown member';const joined=p.forum_profiles?.created_at?new Date(p.forum_profiles.created_at).toLocaleDateString():'';const rx=reactionMap[p.id]||{like:0,interesting:0,mine:new Set()};const staffButtons=isStaff()?`<button type="button" class="mini-btn ${p.moderation_status==='visible'?'danger-btn':'success-btn'}" data-mod-post="${p.id}:${p.moderation_status==='visible'?'hide':'restore'}">${p.moderation_status==='visible'?'HIDE':'RESTORE'}</button>`:'';return `<article class="post ${p.moderation_status!=='visible'?'staff-hidden':''}" id="post-${p.id}"><aside class="post-author"><div><button type="button" class="profile-link" data-profile="${p.author_id}"><strong>${esc(name)}</strong></button>${roleBadge(p.forum_profiles?.role)}<span>${esc(p.forum_profiles?.username?'@'+p.forum_profiles.username:'')}</span></div><span>JOINED ${esc(joined)}</span></aside><div class="post-body"><div class="post-text">${esc(p.body)}</div><div class="post-tools"><button type="button" class="mini-btn" data-react="${p.id}:like">${rx.mine.has('like')?'UNLIKE':'LIKE'} (${rx.like||0})</button><button type="button" class="mini-btn" data-react="${p.id}:interesting">${rx.mine.has('interesting')?'REMOVE INTEREST':'INTERESTING'} (${rx.interesting||0})</button><button type="button" class="mini-btn" data-report-post="${p.id}">REPORT</button>${staffButtons}<span class="thread-meta">#${index+1} · ${esc(fmt(p.created_at))}${p.moderation_status!=='visible'?' · HIDDEN':''}</span></div></div></article>`}).join('');
    els.threadPosts.querySelectorAll('[data-react]').forEach(b=>b.addEventListener('click',()=>toggleReaction(b.dataset.react)));
    els.threadPosts.querySelectorAll('[data-report-post]').forEach(b=>b.addEventListener('click',()=>reportTarget('post',b.dataset.reportPost)));
    els.threadPosts.querySelectorAll('[data-mod-post]').forEach(b=>b.addEventListener('click',()=>{const[id,action]=b.dataset.modPost.split(':');moderatePost(id,action)}));wireProfileLinks(els.threadPosts)
  }

  function wireProfileLinks(root=document){root?.querySelectorAll('[data-profile]').forEach(b=>b.addEventListener('click',()=>showProfile(b.dataset.profile)))}
  async function toggleReaction(spec){if(!requireProfile())return;const[postId,reaction]=spec.split(':');const{data}=await client.from('forum_reactions').select('post_id').eq('post_id',postId).eq('user_id',session.user.id).eq('reaction',reaction).maybeSingle();let error;if(data){({error}=await client.from('forum_reactions').delete().eq('post_id',postId).eq('user_id',session.user.id).eq('reaction',reaction))}else{({error}=await client.from('forum_reactions').insert({post_id:postId,user_id:session.user.id,reaction}))}if(error)showNotice(error.message,'error');else await renderPosts(activePosts)}

  async function reportTarget(type,id){if(!requireProfile())return;const reason=prompt(`Brief reason for reporting this ${type}:`);if(!reason?.trim())return;const{error}=await client.rpc('forum_submit_report',{p_target_type:type,p_target_id:id,p_reason:reason.trim().slice(0,100),p_details:null});if(error)showNotice(error.message,'error');else showNotice('Report submitted for moderator review.','success')}

  async function refreshAuth(){const{data}=await client.auth.getSession();session=data.session;profile=null;if(session?.user){const{data:p}=await client.from('forum_profiles').select('id,username,display_name,bio,avatar_url,role,created_at').eq('id',session.user.id).maybeSingle();profile=p||null}renderAuth();if(activeThread){els.replyForm.classList.toggle('hidden',!session||!profile||activeThread.is_locked);renderStaffThreadTools()}}
  function renderAuth(){els.newThreadBtn.disabled=!session||!profile;if(!session){els.authState.textContent='Reading as guest. Sign in to post, react, bookmark, or report.';els.authActions.innerHTML='<button class="bbs-btn" type="button" id="openLoginBtn">SIGN IN / REGISTER</button>';$('#openLoginBtn')?.addEventListener('click',()=>openModal(els.loginModal));els.profileSetup.classList.add('hidden');return}if(!profile){els.authState.textContent=`Signed in as ${session.user.email}. Create your public forum username to participate.`;els.authActions.innerHTML='<button class="bbs-btn secondary" type="button" id="logoutBtn">SIGN OUT</button>';$('#logoutBtn')?.addEventListener('click',logout);els.profileSetup.classList.remove('hidden');return}els.profileSetup.classList.add('hidden');els.authState.innerHTML=`Logged in as <strong>${esc(profile.display_name||profile.username)}</strong> (@${esc(profile.username)}) ${roleBadge(profile.role)}`;els.authActions.innerHTML=`<button class="bbs-btn secondary" type="button" id="myProfileBtn">MY PROFILE</button>${isStaff()?'<button class="bbs-btn warning-btn" type="button" id="staffBtn">STAFF CONSOLE</button>':''}<button class="bbs-btn secondary" type="button" id="logoutBtn">SIGN OUT</button>`;$('#myProfileBtn')?.addEventListener('click',()=>showProfile(profile.id,true));$('#staffBtn')?.addEventListener('click',openStaffConsole);$('#logoutBtn')?.addEventListener('click',logout)}
  function requireProfile(){if(!session){openModal(els.loginModal);return false}if(!profile){showNotice('Create your forum username first.','error');return false}return true}
  async function logout(){await client.auth.signOut();session=null;profile=null;renderAuth();showNotice('Signed out.')}

  async function saveProfile(){if(!session)return;const username=els.usernameInput.value.trim().toLowerCase(),displayName=els.displayNameInput.value.trim();if(!/^[a-z0-9_]{3,24}$/.test(username)){showNotice('Username must be 3–24 characters using lowercase letters, numbers, or underscores.','error');return}const{error}=await client.from('forum_profiles').insert({id:session.user.id,username,display_name:displayName||null});if(error){showNotice(error.code==='23505'?'That username is already taken.':error.message,'error');return}await refreshAuth();showNotice('Forum profile created.','success')}
  async function handleLogin(e){e.preventDefault();const fd=new FormData(e.currentTarget);const{error}=await client.auth.signInWithPassword({email:String(fd.get('email')).trim(),password:String(fd.get('password'))});if(error){showNotice(error.message,'error');return}closeModal(els.loginModal);e.currentTarget.reset();await refreshAuth();showNotice('Signed in.','success')}
  async function handleSignup(e){e.preventDefault();const fd=new FormData(e.currentTarget),email=String(fd.get('email')).trim(),password=String(fd.get('password'));const{data,error}=await client.auth.signUp({email,password,options:{emailRedirectTo:`${location.origin}/forum/`}});if(error){showNotice(error.message,'error');return}e.currentTarget.reset();if(data.session){closeModal(els.loginModal);await refreshAuth();showNotice('Account created. Choose your forum username.','success')}else showNotice('Check your email to confirm the account, then return here and sign in.','success')}

  async function handleNewThread(e){e.preventDefault();if(!requireProfile())return;const categoryId=Number(els.threadCategory.value),title=els.threadTitle.value.trim(),body=els.threadBody.value.trim(),entityId=els.entityId.value.trim(),entityName=els.entityName.value.trim();const{data,error}=await client.rpc('forum_create_thread',{p_category_id:categoryId,p_title:title,p_body:body,p_entity_id:entityId&&entityName?entityId:null,p_entity_name:entityId&&entityName?entityName:null});if(error){showNotice(error.message,'error');return}e.currentTarget.reset();closeModal(els.newThreadModal);await Promise.all([loadLatestThreads(),loadStats()]);await openThread(data);showNotice('Discussion posted.','success')}
  async function handleReply(e){e.preventDefault();if(!activeThread||!requireProfile())return;const body=els.replyBody.value.trim();if(!body)return;const{error}=await client.rpc('forum_create_post',{p_thread_id:activeThread.id,p_body:body,p_reply_to:null});if(error){showNotice(error.message,'error');return}els.replyBody.value='';await Promise.all([openThread(activeThread.id,false),loadStats()]);showNotice('Reply posted.','success')}

  async function toggleBookmark(){if(!activeThread||!requireProfile())return;const{data}=await client.from('forum_bookmarks').select('thread_id').eq('user_id',session.user.id).eq('thread_id',activeThread.id).maybeSingle();let error;if(data)({error}=await client.from('forum_bookmarks').delete().eq('user_id',session.user.id).eq('thread_id',activeThread.id));else({error}=await client.from('forum_bookmarks').insert({user_id:session.user.id,thread_id:activeThread.id}));if(error)showNotice(error.message,'error');else await updateBookmarkState()}
  async function updateBookmarkState(){els.bookmarkBtn.disabled=!session||!profile||!activeThread;if(!session||!profile||!activeThread){els.bookmarkBtn.textContent='BOOKMARK';return}const{data}=await client.from('forum_bookmarks').select('thread_id').eq('user_id',session.user.id).eq('thread_id',activeThread.id).maybeSingle();els.bookmarkBtn.textContent=data?'BOOKMARKED':'BOOKMARK'}

  async function showProfile(userId,editing=false){const{data:p,error}=await client.from('forum_profiles').select('id,username,display_name,bio,role,created_at').eq('id',userId).single();if(error||!p){showNotice('Profile unavailable.','error');return}const mine=session?.user?.id===p.id;let restriction=null;if(isStaff()){const{data:r}=await client.from('forum_member_restrictions').select('suspended_until,reason').eq('user_id',p.id).maybeSingle();restriction=r||null}els.profileContent.innerHTML=`<div class="profile-card"><div class="profile-meta"><strong>${esc(p.display_name||p.username)}</strong>${roleBadge(p.role)}<br>@${esc(p.username)}<br>JOINED ${esc(new Date(p.created_at).toLocaleDateString())}${restriction?`<div class="suspension-note">SUSPENDED${restriction.suspended_until?' UNTIL '+esc(fmt(restriction.suspended_until)):' INDEFINITELY'}<br>${esc(restriction.reason||'')}</div>`:''}</div><div><div class="profile-bio">${esc(p.bio||'No profile biography.')}</div><div class="profile-actions">${mine?'<button class="bbs-btn secondary" id="editProfileBtn" type="button">EDIT PROFILE</button>':''}${isStaff()&&!mine?`<button class="bbs-btn danger-btn" id="suspendMemberBtn" type="button">SUSPEND MEMBER</button>${restriction?'<button class="bbs-btn success-btn" id="unsuspendMemberBtn" type="button">UNSUSPEND</button>':''}`:''}${isAdmin()&&!mine?'<button class="bbs-btn warning-btn" id="setRoleBtn" type="button">SET ROLE</button>':''}</div><div id="profileEditArea"></div></div></div>`;openModal(els.profileModal);if(mine){$('#editProfileBtn')?.addEventListener('click',()=>renderProfileEditor(p));if(editing)renderProfileEditor(p)}if(isStaff()&&!mine){$('#suspendMemberBtn')?.addEventListener('click',()=>suspendMember(p.id));$('#unsuspendMemberBtn')?.addEventListener('click',()=>unsuspendMember(p.id))}if(isAdmin()&&!mine)$('#setRoleBtn')?.addEventListener('click',()=>setRole(p.id))}
  function renderProfileEditor(p){$('#profileEditArea').innerHTML=`<div class="field" style="margin-top:12px"><label>Display name</label><input id="editDisplayName" maxlength="60" value="${esc(p.display_name||'')}"></div><div class="field" style="margin-top:8px"><label>Bio</label><textarea id="editBio" maxlength="1000">${esc(p.bio||'')}</textarea></div><div class="field-help">Your username is permanent in v1. Display name and bio can be changed.</div><button class="bbs-btn" id="saveProfileEditBtn" type="button" style="margin-top:8px">SAVE PROFILE</button>`;$('#saveProfileEditBtn').addEventListener('click',saveProfileEdit)}
  async function saveProfileEdit(){const displayName=$('#editDisplayName').value.trim(),bio=$('#editBio').value.trim();const{error}=await client.from('forum_profiles').update({display_name:displayName||null,bio:bio||null}).eq('id',session.user.id);if(error){showNotice(error.message,'error');return}closeModal(els.profileModal);await refreshAuth();showNotice('Profile updated.','success')}

  function renderStaffThreadTools(){if(!els.staffThreadTools)return;if(!isStaff()||!activeThread){els.staffThreadTools.classList.add('hidden');els.staffThreadTools.innerHTML='';return}els.staffThreadTools.classList.remove('hidden');els.staffThreadTools.innerHTML=`<strong>STAFF THREAD CONTROLS</strong><div class="compact-actions"><button class="bbs-btn secondary" data-mod-thread="${activeThread.is_pinned?'unpin':'pin'}">${activeThread.is_pinned?'UNPIN':'PIN'}</button><button class="bbs-btn secondary" data-mod-thread="${activeThread.is_locked?'unlock':'lock'}">${activeThread.is_locked?'UNLOCK':'LOCK'}</button><button class="bbs-btn danger-btn" data-mod-thread="hide">HIDE THREAD</button></div>`;els.staffThreadTools.querySelectorAll('[data-mod-thread]').forEach(b=>b.addEventListener('click',()=>moderateThread(b.dataset.modThread)))}
  async function moderateThread(action){if(!isStaff()||!activeThread)return;const note=prompt(`Optional staff note for ${action}:`)||null;const{error}=await client.rpc('forum_moderate_thread',{p_thread_id:activeThread.id,p_action:action,p_note:note});if(error){showNotice(error.message,'error');return}if(action==='hide'){showNotice('Thread hidden.','success');showHome();await loadLatestThreads();return}await openThread(activeThread.id,false);showNotice(`Thread ${action} complete.`,'success')}
  async function moderatePost(postId,action){if(!isStaff())return;const note=prompt(`Optional staff note for ${action}:`)||null;const{error}=await client.rpc('forum_moderate_post',{p_post_id:postId,p_action:action,p_note:note});if(error){showNotice(error.message,'error');return}await openThread(activeThread.id,false);showNotice(`Post ${action} complete.`,'success')}
  async function suspendMember(userId){const amount=prompt('Suspend for how many hours? Enter 0 for indefinite:','24');if(amount===null)return;const hours=Number(amount);if(!Number.isFinite(hours)||hours<0){showNotice('Invalid suspension duration.','error');return}const reason=prompt('Reason for suspension:');if(!reason?.trim())return;const until=hours===0?null:new Date(Date.now()+hours*3600000).toISOString();const{error}=await client.rpc('forum_suspend_member',{p_user_id:userId,p_until:until,p_reason:reason.trim()});if(error)showNotice(error.message,'error');else{showNotice('Member suspended.','success');showProfile(userId)}}
  async function unsuspendMember(userId){const{error}=await client.rpc('forum_unsuspend_member',{p_user_id:userId,p_note:'Staff console unsuspension'});if(error)showNotice(error.message,'error');else{showNotice('Suspension removed.','success');showProfile(userId)}}
  async function setRole(userId){const role=prompt('Set role: member, moderator, or admin','member')?.trim().toLowerCase();if(!role)return;const{error}=await client.rpc('forum_set_role',{p_user_id:userId,p_role:role});if(error)showNotice(error.message,'error');else{showNotice(`Role changed to ${role}.`,'success');showProfile(userId)}}

  async function openStaffConsole(){if(!isStaff())return;els.staffContent.innerHTML='<div class="staff-empty">Loading moderation queue…</div>';openModal(els.staffModal);const[{data:reports},{data:actions}]=await Promise.all([client.from('forum_reports').select('id,target_type,thread_id,post_id,profile_id,reason,details,status,created_at,reporter_id').eq('status','open').order('created_at',{ascending:true}).limit(50),client.from('forum_moderation_actions').select('id,action,target_type,target_id,note,created_at,actor_id').order('created_at',{ascending:false}).limit(20)]);els.staffContent.innerHTML=`<div class="staff-console-grid"><div><div class="panel-title"><span>Open Reports</span></div><div>${reports?.length?reports.map(renderReport).join(''):'<div class="staff-empty">No open reports.</div>'}</div></div><div><div class="panel-title"><span>Member Lookup</span></div><div class="panel-body"><div class="field"><label>Username</label><input id="staffMemberSearch" placeholder="username"></div><button class="bbs-btn secondary" id="staffMemberSearchBtn" type="button" style="margin-top:7px">FIND MEMBER</button><div id="staffMemberResult"></div></div><div class="panel-title" style="margin-top:12px"><span>Recent Staff Actions</span></div><div>${actions?.length?actions.map(a=>`<div class="audit-row"><div>${esc(a.action)} → ${esc(a.target_type)} ${esc(a.target_id)}</div><div class="audit-meta">${esc(fmt(a.created_at))}${a.note?' · '+esc(a.note):''}</div></div>`).join(''):'<div class="staff-empty">No staff actions yet.</div>'}</div></div></div>`;els.staffContent.querySelectorAll('[data-resolve-report]').forEach(b=>b.addEventListener('click',()=>resolveReport(b.dataset.resolveReport,'resolved')));els.staffContent.querySelectorAll('[data-dismiss-report]').forEach(b=>b.addEventListener('click',()=>resolveReport(b.dataset.dismissReport,'dismissed')));els.staffContent.querySelectorAll('[data-report-target]').forEach(b=>b.addEventListener('click',()=>openReportTarget(b.dataset.reportTarget)));$('#staffMemberSearchBtn')?.addEventListener('click',staffMemberSearch)}
  function renderReport(r){const id=r.thread_id||r.post_id||r.profile_id||'';return `<div class="report-row"><div class="report-title">${esc(r.target_type.toUpperCase())} REPORT · ${esc(r.reason)}</div><div class="report-meta">${esc(fmt(r.created_at))} · target ${esc(id)}</div>${r.details?`<div>${esc(r.details)}</div>`:''}<div class="compact-actions"><button class="bbs-btn secondary" data-report-target="${esc(r.target_type+':'+id)}">OPEN TARGET</button><button class="bbs-btn success-btn" data-resolve-report="${r.id}">RESOLVE</button><button class="bbs-btn secondary" data-dismiss-report="${r.id}">DISMISS</button></div></div>`}
  async function resolveReport(id,status){const note=prompt(`Optional resolution note (${status}):`)||null;const{error}=await client.rpc('forum_resolve_report',{p_report_id:id,p_status:status,p_note:note});if(error)showNotice(error.message,'error');else{showNotice(`Report ${status}.`,'success');openStaffConsole()}}
  async function openReportTarget(spec){const[type,id]=spec.split(':');if(type==='thread'){closeModal(els.staffModal);return openThread(id)}if(type==='profile'){closeModal(els.staffModal);return showProfile(id)}if(type==='post'){const{data}=await client.from('forum_posts').select('thread_id').eq('id',id).single();if(data){closeModal(els.staffModal);await openThread(data.thread_id);setTimeout(()=>document.getElementById(`post-${id}`)?.scrollIntoView({behavior:'smooth',block:'center'}),100)}}}
  async function staffMemberSearch(){const q=$('#staffMemberSearch').value.trim();if(!q)return;const{data,error}=await client.from('forum_profiles').select('id,username,display_name,role').ilike('username',q).limit(10);const target=$('#staffMemberResult');if(error){target.textContent=error.message;return}target.innerHTML=(data||[]).length?(data||[]).map(p=>`<div class="member-row"><button class="profile-link" data-staff-profile="${p.id}"><strong>@${esc(p.username)}</strong></button>${roleBadge(p.role)}<div class="muted">${esc(p.display_name||'')}</div></div>`).join(''):'<div class="staff-empty">No member found.</div>';target.querySelectorAll('[data-staff-profile]').forEach(b=>b.addEventListener('click',()=>{closeModal(els.staffModal);showProfile(b.dataset.staffProfile)}))}

  function showHome(push=true){if(push)history.pushState({},'','/forum/');activeThread=null;activePosts=[];els.threadView.classList.add('hidden');els.forumHome.classList.remove('hidden');els.mainTitle.textContent='Archive Boards';renderCategories();loadLatestThreads();loadStats();renderBreadcrumbs([{label:'Forum'}])}
  async function routeFromUrl(){const qs=new URLSearchParams(location.search),thread=qs.get('thread'),category=qs.get('category');if(thread)return openThread(thread,false);showHome(false);if(category)return loadCategory(category,false)}

  function wireEvents(){document.querySelectorAll('[data-close-modal]').forEach(b=>b.addEventListener('click',()=>closeModal(b.closest('.modal-backdrop'))));document.querySelectorAll('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m)}));els.loginForm.addEventListener('submit',handleLogin);els.signupForm.addEventListener('submit',handleSignup);els.saveProfileBtn.addEventListener('click',saveProfile);els.newThreadBtn.addEventListener('click',()=>requireProfile()&&openModal(els.newThreadModal));els.newThreadForm.addEventListener('submit',handleNewThread);els.replyForm.addEventListener('submit',handleReply);els.bookmarkBtn.addEventListener('click',toggleBookmark);els.threadReportBtn.addEventListener('click',()=>activeThread&&reportTarget('thread',activeThread.id));$('#forumHomeBtn')?.addEventListener('click',()=>showHome());window.addEventListener('popstate',routeFromUrl);client.auth.onAuthStateChange(()=>setTimeout(refreshAuth,0))}

  async function init(){wireEvents();try{await Promise.all([loadCategories(),refreshAuth(),loadStats()]);await loadLatestThreads();await routeFromUrl()}catch(err){console.error(err);showNotice('The forum database could not be reached.','error')}}
  init();
})();