(()=>{'use strict';
const C=window.ForumCore,M=window.ForumCommunity;
const {db,state,$,$$,esc,fmt,rel,displayName,avatar,badge,urlFor,flash,openModal,closeModal,profiles}=C;
const MEDIA_BUCKET='forum-dm-media',MAX_MEDIA=50*1024*1024;
const MEDIA_TYPES=new Set(['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm','video/quicktime']);
const S={conversation:null,partner:null,channel:null,userChannel:null,channelId:null,typingTimer:null,typingSentAt:0,pc:null,localStream:null,remoteStream:null,incoming:null,callPeer:null};
function signedIn(){return !!(state.session&&state.profile)}
function pairOther(c){return c.user_one===state.profile?.id?c.user_two:c.user_one}
function ownReadAt(c){return c.user_one===state.profile?.id?c.read_at_one:c.read_at_two}
function activeMessagesTab(on=true){C.activeTab(on?'messages':'')}
function socialButton(label,action,target,extra=''){return `<button class="bbs-btn secondary" type="button" data-social-action="${esc(action)}" data-social-target="${esc(target)}" ${extra}>${esc(label)}</button>`}
async function unreadCount(){if(!signedIn())return 0;const uid=state.profile.id,{data,error}=await db.from('forum_direct_conversations').select('id,user_one,user_two,status,read_at_one,read_at_two,last_message_at').or(`user_one.eq.${uid},user_two.eq.${uid}`).in('status',['active','pending']);if(error)return 0;return (data||[]).filter(c=>c.last_message_at&&(!ownReadAt(c)||new Date(c.last_message_at)>new Date(ownReadAt(c)))).length}
async function refreshNav(){let tab=$('#messagesTab');if(!tab){tab=document.createElement('a');tab.id='messagesTab';tab.className='forum-tab hidden';tab.dataset.navView='messages';tab.href='/forum/?view=messages';tab.textContent='MESSAGES';$('#forumTabs')?.insertBefore(tab,$('#bookmarksTab')||null)}if(!signedIn()){tab?.classList.add('hidden');await teardownUserChannel();return}tab?.classList.remove('hidden');const n=await unreadCount();tab.textContent=n?`MESSAGES (${n})`:'MESSAGES';const menu=$('#accountMenu');if(menu&&!menu.querySelector('[data-social-menu="friends"]')){const first=menu.firstElementChild;const msg=document.createElement('a');msg.setAttribute('role','menuitem');msg.dataset.route='';msg.dataset.socialMenu='messages';msg.href='/forum/?view=messages';msg.textContent=n?`PRIVATE MESSAGES (${n})`:'PRIVATE MESSAGES';const fr=document.createElement('a');fr.setAttribute('role','menuitem');fr.dataset.route='';fr.dataset.socialMenu='friends';fr.href='/forum/?view=friends';fr.textContent='FRIENDS';if(first){menu.insertBefore(fr,first);menu.insertBefore(msg,fr)}else{menu.append(msg,fr)}}else if(menu){const msg=menu.querySelector('[data-social-menu="messages"]');if(msg)msg.textContent=n?`PRIVATE MESSAGES (${n})`:'PRIVATE MESSAGES'}await setupUserChannel()}
async function relationship(target){if(!signedIn()||!target||target===state.profile.id)return{friendship:null,blocked:false};const uid=state.profile.id,[fr,bl]=await Promise.all([db.from('forum_friendships').select('id,user_one,user_two,requested_by,status,updated_at').or(`user_one.eq.${target},user_two.eq.${target}`).maybeSingle(),db.from('forum_blocks').select('blocked_id').eq('blocker_id',uid).eq('blocked_id',target).maybeSingle()]);return{friendship:fr.data||null,blocked:!!bl.data}}
async function decorateProfile(userId){if(!signedIn()||!userId||userId===state.profile.id)return;const actions=$('#profileContent .profile-actions');if(!actions)return;actions.querySelector('.social-profile-actions')?.remove();const {friendship,blocked}=await relationship(userId),wrap=document.createElement('div');wrap.className='social-profile-actions';wrap.dataset.socialProfile=userId;if(blocked){wrap.innerHTML=socialButton('UNBLOCK','unblock',userId);actions.append(wrap);return}let html='';if(friendship?.status==='accepted'){html+=socialButton('MESSAGE','message',userId);html+=socialButton('REMOVE FRIEND','remove-friend',userId);}
else if(friendship?.status==='pending'&&friendship.requested_by===state.profile.id){html+='<button class="bbs-btn secondary" type="button" disabled>FRIEND REQUEST SENT</button>'+socialButton('CANCEL REQUEST','cancel-friend',userId)+socialButton('MESSAGE REQUEST','message',userId)}
else if(friendship?.status==='pending'){html+=socialButton('ACCEPT FRIEND','accept-friend',friendship.id)+socialButton('DECLINE','decline-friend',friendship.id)+socialButton('MESSAGE','message',userId)}
else{html+=socialButton('ADD FRIEND','add-friend',userId)+socialButton('MESSAGE','message',userId)}
html+=socialButton('BLOCK','block',userId);wrap.innerHTML=html;actions.append(wrap)}
const baseShowProfile=M.showProfile.bind(M);M.showProfile=async function(userId,edit=false){await baseShowProfile(userId,edit);await decorateProfile(userId)};
async function doSocialAction(action,target){try{if(!signedIn())return C.requireProfile();const openProfileId=$('#profileContent .social-profile-actions')?.dataset.socialProfile;let r=null;if(action==='add-friend')r=await db.rpc('forum_send_friend_request',{p_target:target});
else if(action==='accept-friend')r=await db.rpc('forum_respond_friend_request',{p_friendship:target,p_action:'accept'});
else if(action==='decline-friend')r=await db.rpc('forum_respond_friend_request',{p_friendship:target,p_action:'decline'});
else if(action==='cancel-friend')r=await db.rpc('forum_cancel_friend_request',{p_target:target});
else if(action==='remove-friend'){if(!confirm('Remove this member from your friends?'))return;r=await db.rpc('forum_remove_friend',{p_target:target})}
else if(action==='block'){if(!confirm('Block this member? They will no longer be able to friend or message you.'))return;r=await db.rpc('forum_block_member',{p_target:target});}
else if(action==='unblock')r=await db.rpc('forum_unblock_member',{p_target:target});
else if(action==='message'){const{data,error}=await db.rpc('forum_open_direct_conversation',{p_target:target});if(error)throw error;return C.navigate({dm:data})}
else if(action==='accept-message'||action==='decline-message'){const verb=action==='accept-message'?'accept':'decline';r=await db.rpc('forum_respond_message_request',{p_conversation:target,p_action:verb});}
if(r?.error)throw r.error;await refreshNav();if(openProfileId)await M.showProfile(openProfileId);else await window.ForumApp.route();flash('Community connection updated.','success')}catch(e){flash(e.message||'Unable to update this connection.','error')}}
async function loadConnections(){if(!signedIn())return null;const uid=state.profile.id;const [fr,bl]=await Promise.all([db.from('forum_friendships').select('id,user_one,user_two,requested_by,status,created_at,updated_at').or(`user_one.eq.${uid},user_two.eq.${uid}`).order('updated_at',{ascending:false}),db.from('forum_blocks').select('blocked_id,created_at').eq('blocker_id',uid).order('created_at',{ascending:false})]);if(fr.error)throw fr.error;if(bl.error)throw bl.error;const ids=[...(fr.data||[]).flatMap(x=>[x.user_one,x.user_two]),...(bl.data||[]).map(x=>x.blocked_id)].filter(x=>x!==uid),pm=await profiles(ids);return{friendships:fr.data||[],blocks:bl.data||[],profiles:pm}}
function memberCard(p,buttons=''){return `<article class="social-member-card"><div class="social-member-main">${avatar(p,'sm')}<div><a href="#" data-profile="${esc(p.id)}"><strong>${esc(displayName(p))}</strong></a> ${badge(p.role)}<div class="author-handle">@${esc(p.username)}</div></div></div><div class="social-member-actions">${buttons}</div></article>`}
async function renderFriends(){activeMessagesTab();C.crumbs([{label:'Forum',href:'/forum/'},{label:'Friends'}]);if(!signedIn()){C.requireProfile();return}const data=await loadConnections(),uid=state.profile.id,incoming=[],outgoing=[],friends=[];for(const f of data.friendships){const other=f.user_one===uid?f.user_two:f.user_one,p=data.profiles.get(other);if(!p)continue;if(f.status==='accepted')friends.push({f,p});else if(f.status==='pending'&&f.requested_by===uid)outgoing.push({f,p});else if(f.status==='pending')incoming.push({f,p})}const blocked=data.blocks.map(b=>data.profiles.get(b.blocked_id)).filter(Boolean);$('#forumContent').innerHTML=C.pageHead('COMMUNITY','Friends','Connect with people you meet in paranormal discussions. Friends can message each other directly.',`<a class="bbs-btn secondary" data-route href="/forum/?view=messages">PRIVATE MESSAGES</a>`)+`<section class="panel"><div class="panel-title">FIND A MEMBER</div><form id="friendSearchForm" class="social-search"><input id="friendSearchInput" maxlength="40" placeholder="Search username or display name…"><button class="bbs-btn primary">SEARCH</button></form><div id="friendSearchResults"></div></section><section class="panel social-section"><div class="panel-title">FRIEND REQUESTS <span>${incoming.length}</span></div><div>${incoming.length?incoming.map(({f,p})=>memberCard(p,socialButton('ACCEPT','accept-friend',f.id)+socialButton('DECLINE','decline-friend',f.id))).join(''):'<div class="empty-state">No incoming friend requests.</div>'}</div></section><section class="panel social-section"><div class="panel-title">FRIENDS <span>${friends.length}</span></div><div>${friends.length?friends.map(({p})=>memberCard(p,socialButton('MESSAGE','message',p.id)+socialButton('REMOVE','remove-friend',p.id))).join(''):'<div class="empty-state">You have not added any friends yet.</div>'}</div></section>${outgoing.length?`<section class="panel social-section"><div class="panel-title">SENT REQUESTS</div>${outgoing.map(({p})=>memberCard(p,'<span class="status">PENDING</span>'+socialButton('CANCEL','cancel-friend',p.id))).join('')}</section>`:''}${blocked.length?`<section class="panel social-section"><div class="panel-title">BLOCKED MEMBERS</div>${blocked.map(p=>memberCard(p,socialButton('UNBLOCK','unblock',p.id))).join('')}</section>`:''}`}
async function searchMembers(){const q=$('#friendSearchInput')?.value.trim();if(!q||q.length<2)return;const pattern=`%${q.replaceAll('%','\\%').replaceAll('_','\\_')}%`,{data,error}=await db.from('forum_profiles').select('id,username,display_name,bio,avatar_url,role,created_at').or(`username.ilike.${pattern},display_name.ilike.${pattern}`).neq('id',state.profile.id).limit(20);if(error)return flash(error.message,'error');$('#friendSearchResults').innerHTML=(data||[]).length?(data||[]).map(p=>memberCard(p,socialButton('OPEN PROFILE','profile',p.id))).join(''):'<div class="empty-state">No members found.</div>'}
async function conversationRows(){const uid=state.profile.id,{data,error}=await db.from('forum_direct_conversations').select('id,user_one,user_two,requested_by,status,read_at_one,read_at_two,created_at,updated_at,last_message_at').or(`user_one.eq.${uid},user_two.eq.${uid}`).in('status',['active','pending']).order('last_message_at',{ascending:false,nullsFirst:false}).order('updated_at',{ascending:false});if(error)throw error;const convs=data||[],pm=await profiles(convs.map(pairOther)),ids=convs.map(c=>c.id);let lm=new Map();if(ids.length){const r=await db.from('forum_private_messages').select('id,conversation_id,sender_id,body,attachment_name,attachment_mime,created_at').in('conversation_id',ids).order('created_at',{ascending:false}).limit(250);if(r.error)throw r.error;for(const m of r.data||[])if(!lm.has(m.conversation_id))lm.set(m.conversation_id,m)}return convs.map(c=>({c,p:pm.get(pairOther(c)),last:lm.get(c.id),unread:!!(c.last_message_at&&(!ownReadAt(c)||new Date(c.last_message_at)>new Date(ownReadAt(c))))}))}
function conversationCard(x){const {c,p,last,unread}=x,request=c.status==='pending',incoming=request&&c.requested_by!==state.profile.id,preview=last?.body||last?.attachment_name||(request?'Message request':'No messages yet');return `<article class="dm-row ${unread?'unread':''}"><a class="dm-row-main" data-route href="${urlFor({dm:c.id})}">${avatar(p,'sm')}<span class="dm-row-copy"><strong>${esc(displayName(p))} ${unread?'<span class="status">NEW</span>':''}</strong><span>@${esc(p?.username||'member')}</span><span>${esc(preview)}</span></span></a><div class="dm-row-meta"><span>${esc(rel(c.last_message_at||c.updated_at))}</span>${incoming?`<div>${socialButton('ACCEPT','accept-message',c.id)}${socialButton('DECLINE','decline-message',c.id)}</div>`:request?'<span class="status">REQUEST SENT</span>':''}</div></article>`}
async function renderMessages(){activeMessagesTab();C.crumbs([{label:'Forum',href:'/forum/'},{label:'Messages'}]);if(!signedIn()){C.requireProfile();return}const rows=await conversationRows(),incoming=rows.filter(x=>x.c.status==='pending'&&x.c.requested_by!==state.profile.id),rest=rows.filter(x=>!incoming.includes(x));$('#forumContent').innerHTML=C.pageHead('PRIVATE COMMUNITY','Messages','One-to-one conversations. Non-friends arrive as message requests before a conversation opens.',`<a class="bbs-btn secondary" data-route href="/forum/?view=friends">FRIENDS & REQUESTS</a>`)+`${incoming.length?`<section class="panel"><div class="panel-title">MESSAGE REQUESTS <span>${incoming.length}</span></div>${incoming.map(conversationCard).join('')}</section>`:''}<section class="panel ${incoming.length?'social-section':''}"><div class="panel-title">CONVERSATIONS</div>${rest.length?rest.map(conversationCard).join(''):'<div class="empty-state">No private conversations yet. Open a member profile and choose MESSAGE.</div>'}</section>`;await refreshNav()}
async function getConversation(id){const{data,error}=await db.from('forum_direct_conversations').select('id,user_one,user_two,requested_by,status,read_at_one,read_at_two,created_at,updated_at,last_message_at').eq('id',id).maybeSingle();if(error)throw error;if(!data)throw new Error('Private conversation unavailable.');const pm=await profiles([pairOther(data)]);return{c:data,p:pm.get(pairOther(data))}}
function messageBubble(m){const mine=m.sender_id===state.profile.id,media=m.attachment_path?`<div class="dm-attachment" data-path="${esc(m.attachment_path)}" data-mime="${esc(m.attachment_mime||'')}" data-name="${esc(m.attachment_name||'attachment')}"><span>LOADING PRIVATE MEDIA…</span></div>`:'';return `<article class="dm-message ${mine?'mine':'theirs'}" id="dm-message-${m.id}"><div class="dm-bubble">${m.body?`<div class="dm-text">${esc(m.body)}</div>`:''}${media}<div class="dm-time">${esc(fmt(m.created_at))}</div></div></article>`}
async function fetchMessages(id){const{data,error}=await db.from('forum_private_messages').select('id,conversation_id,sender_id,body,attachment_path,attachment_name,attachment_mime,attachment_size,created_at,updated_at').eq('conversation_id',id).is('deleted_at',null).order('created_at',{ascending:true}).limit(200);if(error)throw error;return data||[]}
async function resolveMedia(root=document){for(const el of root.querySelectorAll('.dm-attachment[data-path]')){const path=el.dataset.path,mime=el.dataset.mime,name=el.dataset.name,{data,error}=await db.storage.from(MEDIA_BUCKET).createSignedUrl(path,3600);if(error||!data?.signedUrl){el.innerHTML='<span>PRIVATE MEDIA UNAVAILABLE</span>';continue}const src=esc(data.signedUrl);if(mime.startsWith('image/'))el.innerHTML=`<a href="${src}" target="_blank" rel="noopener"><img src="${src}" alt="${esc(name)}" loading="lazy" referrerpolicy="no-referrer"></a>`;else if(mime.startsWith('video/'))el.innerHTML=`<video src="${src}" controls playsinline preload="metadata"></video><div class="dm-file-name">${esc(name)}</div>`;else el.innerHTML=`<a href="${src}" target="_blank" rel="noopener">${esc(name)}</a>`}}
function composer(c,messages){const mineRequest=c.status==='pending'&&c.requested_by===state.profile.id,canSend=c.status==='active'||(mineRequest&&!messages.length);if(!canSend)return'';const media=c.status==='active'?`<label class="bbs-btn secondary dm-file-button">PHOTO / GIF / VIDEO<input id="dmFile" type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,video/quicktime" hidden></label>`:'';return `<form id="dmComposer" class="dm-composer"><textarea id="dmBody" maxlength="5000" placeholder="Write a private message…"></textarea><div id="dmFilePreview" class="dm-file-preview"></div><div class="dm-compose-actions">${media}<button class="bbs-btn primary" type="submit">SEND</button></div>${mineRequest?'<div class="field-help">This is a message request. You can send one text message; photos and videos unlock after they accept.</div>':'<div class="field-help">Private media: JPG, PNG, WebP, GIF, MP4, WebM or MOV · up to 50 MB.</div>'}</form>`}
async function renderConversation(id){activeMessagesTab();if(!signedIn()){C.requireProfile();return}const {c,p}=await getConversation(id),messages=await fetchMessages(id);S.conversation=c;S.partner=p;C.crumbs([{label:'Forum',href:'/forum/'},{label:'Messages',href:'/forum/?view=messages'},{label:displayName(p)}]);const incoming=c.status==='pending'&&c.requested_by!==state.profile.id,waiting=c.status==='pending'&&c.requested_by===state.profile.id;$('#forumContent').innerHTML=`<section class="dm-shell"><header class="dm-head">${avatar(p,'sm')}<div class="dm-head-copy"><h2>${esc(displayName(p))} ${badge(p?.role)}</h2><span>@${esc(p?.username||'member')}</span><span id="dmPresence" class="dm-presence">OFFLINE</span></div><div class="dm-head-actions"><button class="bbs-btn secondary" type="button" data-profile="${esc(p.id)}">PROFILE</button>${c.status==='active'?'<button class="bbs-btn primary" type="button" data-video-call>VIDEO CALL</button>':''}${socialButton('BLOCK','block',p.id)}</div></header>${incoming?`<div class="dm-request-banner"><strong>MESSAGE REQUEST</strong><span>${esc(displayName(p))} wants to message you.</span><div>${socialButton('ACCEPT','accept-message',c.id)}${socialButton('DECLINE','decline-message',c.id)}</div></div>`:waiting?'<div class="dm-request-banner"><strong>MESSAGE REQUEST SENT</strong><span>They must accept before you can continue the conversation or send media.</span></div>':''}<div id="dmMessages" class="dm-messages">${messages.length?messages.map(messageBubble).join(''):'<div class="empty-state">Start the private conversation.</div>'}</div><div id="dmTyping" class="dm-typing"></div>${composer(c,messages)}</section>`;await resolveMedia($('#forumContent'));await subscribeConversation(c.id);if(c.status==='active'||incoming)await markRead(c.id);bindComposerFile();scrollMessages();await refreshNav()}
function bindComposerFile(){const input=$('#dmFile');if(!input)return;input.addEventListener('change',()=>{const f=input.files?.[0],preview=$('#dmFilePreview');if(!f){preview.innerHTML='';return}if(!MEDIA_TYPES.has(f.type)||f.size>MAX_MEDIA){input.value='';preview.innerHTML='';return flash('Private media must be a supported photo, GIF, or video no larger than 50 MB.','error')}preview.innerHTML=`<span>${esc(f.name)} · ${(f.size/1024/1024).toFixed(1)} MB</span><button class="mini-btn" type="button" data-clear-dm-file>REMOVE</button>`})}
function fileExt(file){const map={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/gif':'gif','video/mp4':'mp4','video/webm':'webm','video/quicktime':'mov'};return map[file.type]||'bin'}
async function sendMessage(form){if(!S.conversation||!signedIn())return;const body=$('#dmBody')?.value.trim()||'',file=$('#dmFile')?.files?.[0]||null,b=form.querySelector('button[type="submit"]');if(!body&&!file)return;if(file&&(!MEDIA_TYPES.has(file.type)||file.size>MAX_MEDIA))return flash('Unsupported private media or file too large.','error');b.disabled=true;b.textContent='SENDING…';let path=null;try{if(file){path=`${S.conversation.id}/${state.profile.id}/${Date.now()}-${crypto.randomUUID().slice(0,8)}.${fileExt(file)}`;const{error:ue}=await db.storage.from(MEDIA_BUCKET).upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(ue)throw ue}const{data,error}=await db.rpc('forum_send_private_message',{p_conversation:S.conversation.id,p_body:body||null,p_attachment_path:path,p_attachment_name:file?.name||null,p_attachment_mime:file?.type||null,p_attachment_size:file?.size||null});if(error)throw error;form.reset();$('#dmFilePreview').innerHTML='';await S.channel?.send({type:'broadcast',event:'message-created',payload:{messageId:data,senderId:state.profile.id}});await refreshConversationMessages();await refreshNav()}catch(e){if(path)db.storage.from(MEDIA_BUCKET).remove([path]).catch(()=>{});flash(e.message||'Unable to send private message.','error')}finally{b.disabled=false;b.textContent='SEND'}}
async function refreshConversationMessages(){if(!S.conversation||new URLSearchParams(location.search).get('dm')!==S.conversation.id)return;const messages=await fetchMessages(S.conversation.id),box=$('#dmMessages');if(!box)return;box.innerHTML=messages.length?messages.map(messageBubble).join(''):'<div class="empty-state">Start the private conversation.</div>';await resolveMedia(box);await markRead(S.conversation.id);scrollMessages()}
function scrollMessages(){const box=$('#dmMessages');if(box)requestAnimationFrame(()=>{box.scrollTop=box.scrollHeight})}
async function markRead(id){const{error}=await db.rpc('forum_mark_conversation_read',{p_conversation:id});if(!error)await S.channel?.send({type:'broadcast',event:'read',payload:{userId:state.profile.id}})}
async function subscribeConversation(id){if(S.channelId===id&&S.channel)return;await teardownConversationChannel();if(state.session?.access_token)db.realtime.setAuth(state.session.access_token);const ch=db.channel(`dm:${id}`,{config:{private:true,presence:{key:state.profile.id}}});ch.on('broadcast',{event:'message-created'},()=>refreshConversationMessages()).on('broadcast',{event:'typing'},({payload})=>{if(payload?.userId===state.profile.id)return;const el=$('#dmTyping');if(!el)return;el.textContent=payload?.typing?`${displayName(S.partner)} is typing…`:'';clearTimeout(S.typingTimer);if(payload?.typing)S.typingTimer=setTimeout(()=>{if(el)el.textContent=''},2500)}).on('broadcast',{event:'call-answer'},({payload})=>handleCallAnswer(payload)).on('broadcast',{event:'call-decline'},()=>{flash('Video call declined.');endCall(false)}).on('broadcast',{event:'call-end'},()=>endCall(false)).on('presence',{event:'sync'},()=>{const el=$('#dmPresence');if(!el)return;const ps=ch.presenceState(),others=Object.values(ps).flat().filter(x=>x.user_id!==state.profile.id);el.textContent=others.length?'ONLINE':'OFFLINE';el.classList.toggle('online',!!others.length)}).subscribe(async status=>{if(status==='SUBSCRIBED'){S.channel=ch;S.channelId=id;await ch.track({user_id:state.profile.id,online_at:new Date().toISOString()})}});S.channel=ch;S.channelId=id}
async function teardownConversationChannel(){if(S.channel){await db.removeChannel(S.channel).catch(()=>{});S.channel=null;S.channelId=null}}
async function setupUserChannel(){if(!signedIn())return teardownUserChannel();const topic=`user:${state.profile.id}`;if(S.userChannel?.topic===`realtime:${topic}`||S.userChannel?.topic===topic)return;if(S.userChannel)await teardownUserChannel();if(state.session?.access_token)db.realtime.setAuth(state.session.access_token);const ch=db.channel(topic,{config:{private:true}}).on('broadcast',{event:'incoming-call'},({payload})=>incomingCall(payload)).subscribe();S.userChannel=ch}
async function teardownUserChannel(){if(S.userChannel){await db.removeChannel(S.userChannel).catch(()=>{});S.userChannel=null}}
async function sendToUser(userId,event,payload){if(state.session?.access_token)db.realtime.setAuth(state.session.access_token);const ch=db.channel(`user:${userId}`,{config:{private:true}});await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(new Error('Unable to reach member.')),5000);ch.subscribe(async(status,err)=>{if(status==='SUBSCRIBED'){clearTimeout(t);try{await ch.send({type:'broadcast',event,payload});resolve()}catch(e){reject(e)}}else if(status==='CHANNEL_ERROR'||status==='TIMED_OUT'){clearTimeout(t);reject(err||new Error('Realtime channel unavailable'))}})});await db.removeChannel(ch).catch(()=>{})}
function injectCallUI(){if($('#videoCallModal'))return;document.body.insertAdjacentHTML('beforeend',`<div id="incomingCallModal" class="modal-backdrop hidden" role="dialog" aria-modal="true"><div class="modal call-incoming"><div class="modal-header"><h2>INCOMING VIDEO CALL</h2></div><div class="modal-body"><div id="incomingCallName" class="call-incoming-name">A member is calling…</div><div class="call-actions"><button class="bbs-btn primary" type="button" data-accept-call>ACCEPT VIDEO</button><button class="bbs-btn danger" type="button" data-decline-call>DECLINE</button></div></div></div></div><div id="videoCallModal" class="modal-backdrop hidden" role="dialog" aria-modal="true"><div class="modal modal-wide video-call-modal"><div class="modal-header"><h2>PRIVATE VIDEO CALL</h2><button class="modal-close" type="button" data-end-call>END CALL</button></div><div class="modal-body"><div id="callStatus" class="call-status">CONNECTING…</div><div class="video-stage"><video id="remoteVideo" autoplay playsinline></video><video id="localVideo" autoplay muted playsinline></video></div><div class="call-actions"><button class="bbs-btn secondary" type="button" data-toggle-mic>MUTE</button><button class="bbs-btn secondary" type="button" data-toggle-camera>CAMERA OFF</button><button class="bbs-btn danger" type="button" data-end-call>END CALL</button></div><div class="field-help">Peer-to-peer video beta. The call itself is not stored by the forum.</div></div></div></div>`)}
async function createPeer(){if(!window.RTCPeerConnection||!navigator.mediaDevices?.getUserMedia)throw new Error('Video calling is not supported by this browser.');cleanupPeer();const stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true}),pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});S.localStream=stream;S.pc=pc;for(const track of stream.getTracks())pc.addTrack(track,stream);pc.ontrack=e=>{S.remoteStream=e.streams[0];const v=$('#remoteVideo');if(v)v.srcObject=S.remoteStream};pc.onconnectionstatechange=()=>{const s=$('#callStatus');if(!s)return;const st=pc.connectionState;s.textContent=st==='connected'?`CONNECTED WITH ${displayName(S.callPeer)}`:st.toUpperCase();if(['failed','disconnected','closed'].includes(st)&&!$('#videoCallModal')?.classList.contains('hidden'))setTimeout(()=>endCall(false),1200)};const lv=$('#localVideo');if(lv)lv.srcObject=stream;return pc}
function waitIce(pc){if(pc.iceGatheringState==='complete')return Promise.resolve();return new Promise(resolve=>{const done=()=>{pc.removeEventListener('icegatheringstatechange',on);clearTimeout(t);resolve()},on=()=>{if(pc.iceGatheringState==='complete')done()},t=setTimeout(done,5000);pc.addEventListener('icegatheringstatechange',on)})}
async function startCall(){if(!S.conversation||S.conversation.status!=='active'||!S.partner)return;try{S.callPeer=S.partner;openModal('#videoCallModal');$('#callStatus').textContent=`CALLING ${displayName(S.partner)}…`;await subscribeConversation(S.conversation.id);const pc=await createPeer(),offer=await pc.createOffer();await pc.setLocalDescription(offer);await waitIce(pc);await sendToUser(S.partner.id,'incoming-call',{conversationId:S.conversation.id,from:state.profile.id,fromName:displayName(state.profile),offer:pc.localDescription});}catch(e){flash(e.message||'Unable to start video call.','error');endCall(false)}}
async function incomingCall(payload){if(!signedIn()||!payload?.conversationId||!payload?.offer)return;try{const{c,p}=await getConversation(payload.conversationId);if(c.status!=='active'||p.id!==payload.from)return;S.incoming={conversation:c,partner:p,offer:payload.offer};$('#incomingCallName').textContent=`${displayName(p)} is calling you.`;openModal('#incomingCallModal')}catch{}}
async function acceptIncoming(){if(!S.incoming)return;try{closeModal('#incomingCallModal');S.conversation=S.incoming.conversation;S.partner=S.incoming.partner;S.callPeer=S.partner;openModal('#videoCallModal');$('#callStatus').textContent=`CONNECTING TO ${displayName(S.partner)}…`;await subscribeConversation(S.conversation.id);const pc=await createPeer();await pc.setRemoteDescription(new RTCSessionDescription(S.incoming.offer));const ans=await pc.createAnswer();await pc.setLocalDescription(ans);await waitIce(pc);await S.channel.send({type:'broadcast',event:'call-answer',payload:{answer:pc.localDescription,from:state.profile.id}});S.incoming=null}catch(e){flash(e.message||'Unable to answer video call.','error');endCall(false)}}
async function declineIncoming(){if(!S.incoming)return;try{S.conversation=S.incoming.conversation;await subscribeConversation(S.conversation.id);await S.channel.send({type:'broadcast',event:'call-decline',payload:{from:state.profile.id}})}catch{}finally{S.incoming=null;closeModal('#incomingCallModal');await teardownConversationChannel()}}
async function handleCallAnswer(payload){if(!S.pc||!payload?.answer)return;try{await S.pc.setRemoteDescription(new RTCSessionDescription(payload.answer));const st=$('#callStatus');if(st)st.textContent=`CONNECTING TO ${displayName(S.callPeer)}…`}catch(e){flash('Video call connection failed.','error');endCall(false)}}
function cleanupPeer(){S.localStream?.getTracks().forEach(t=>t.stop());S.remoteStream?.getTracks().forEach(t=>t.stop());try{S.pc?.close()}catch{}S.pc=null;S.localStream=null;S.remoteStream=null;const lv=$('#localVideo'),rv=$('#remoteVideo');if(lv)lv.srcObject=null;if(rv)rv.srcObject=null}
async function endCall(notify=true){if(notify&&S.channel)await S.channel.send({type:'broadcast',event:'call-end',payload:{from:state.profile?.id}}).catch(()=>{});cleanupPeer();closeModal('#videoCallModal');S.callPeer=null}
function toggleMic(btn){const t=S.localStream?.getAudioTracks()?.[0];if(!t)return;t.enabled=!t.enabled;btn.textContent=t.enabled?'MUTE':'UNMUTE'}
function toggleCamera(btn){const t=S.localStream?.getVideoTracks()?.[0];if(!t)return;t.enabled=!t.enabled;btn.textContent=t.enabled?'CAMERA OFF':'CAMERA ON'}
function typing(){if(!S.channel||!S.conversation||S.conversation.status!=='active')return;const now=Date.now();if(now-S.typingSentAt<700)return;S.typingSentAt=now;S.channel.send({type:'broadcast',event:'typing',payload:{userId:state.profile.id,typing:true}}).catch(()=>{})}
function wire(){document.addEventListener('click',e=>{const a=e.target.closest('[data-social-action]');if(a){e.preventDefault();if(a.dataset.socialAction==='profile')return M.showProfile(a.dataset.socialTarget);doSocialAction(a.dataset.socialAction,a.dataset.socialTarget);return}if(e.target.closest('[data-clear-dm-file]')){const f=$('#dmFile');if(f)f.value='';const p=$('#dmFilePreview');if(p)p.innerHTML='';return}if(e.target.closest('[data-video-call]')){startCall();return}if(e.target.closest('[data-accept-call]')){acceptIncoming();return}if(e.target.closest('[data-decline-call]')){declineIncoming();return}if(e.target.closest('[data-end-call]')){endCall(true);return}const mic=e.target.closest('[data-toggle-mic]');if(mic){toggleMic(mic);return}const cam=e.target.closest('[data-toggle-camera]');if(cam){toggleCamera(cam);return}});document.addEventListener('submit',e=>{if(e.target.matches('#friendSearchForm')){e.preventDefault();searchMembers();return}if(e.target.matches('#dmComposer')){e.preventDefault();sendMessage(e.target);return}});document.addEventListener('input',e=>{if(e.target.matches('#dmBody'))typing()})}
async function onRouteLeave(){const dm=new URLSearchParams(location.search).get('dm');if(!dm&&S.channel&&!S.pc)await teardownConversationChannel()}
async function init(){injectCallUI();wire();await refreshNav()}
window.ForumSocial={init,refreshNav,renderFriends,renderMessages,renderConversation,decorateProfile,onRouteLeave,teardownConversationChannel,teardownUserChannel};
})();